### ISSUE TITLE
GetLocalPath returns blank for Onedrive Business1

### ISSUE THREAD

**Issue by SIFAR786** [cristianbuse/VBA-FileTools#17]
Hi,

This does not seem to work anymore. It was working few weeks ago, but today it is not working any longer. Any reason why this could be happening? It seems to return blank.

```
        spath = GetLocalPath(ThisWorkbook.Path)        
        If InStrRev(spath, "\", -1, vbTextCompare) > 0 Then
            spath = spath & "\"
        End If
        sName = spath & ThisWorkbook.Name

```

**Comment by cristianbuse** [comment]
Hi @SIFAR786 ,

Thanks for raising the issue!

It seems that my tests are still passing. There must be a new Office update that is causing the issue. I will try to get my hands on a computer that has the latest updates and will let you know.

**Comment by cristianbuse** [comment]
Hi @SIFAR786 ,

It seems the latest One Drive update has moved the main ```dat``` file from the regular location. I use that file to correctly map folder names and so the solution doesn't work anymore.

Seems that the gist I linked in my previous post also stopped working as it's based on the same logic. Until I find a solution, you can try using [this](https://stackoverflow.com/questions/33734706/excels-fullname-property-with-onedrive/72736924#72736924)

**Comment by cristianbuse** [comment]
Hi @SIFAR786 ,

I've pushed commit [995ca7f](https://github.com/cristianbuse/VBA-FileTools/commit/995ca7f360371fb70764e0232868919a0b865abf) which now reads the SQLite settings file instead of the old dat file.

It would be great if you could test the new solution. I've already tested on different computers on both x32 and x64 Windows and Mac.

Thanks for your feedback!

**Comment by Greedquest** [comment]
that commit is insane. No sql driver needed I guess

**Comment by cristianbuse** [comment]
Thanks @Greedquest !

Me and Guido are just trying to keep these type of libraries as small as possible with little or no dependencies.

Haven't been in touch for a while. Did you manage to finalize the package manager?

**Comment by Greedquest** [comment]
Hi. Yes keeping it portable is very impressive, although I suppose it's more fragile if the memory layout is the sqlite file changes even though the schema might not.

Package manager I hit a roadblock where it was getting too complex and I also wanted to see the direction RD and tB took on editor integration and language servers. It was also starting to venture into the realms of 100% hobby as opposed to maybe arguably work related, so that slashed the time I could work on it.

Still think it'd be cool to work on more though... I also want to release some good quality projects to host on the package manager too.
