### ISSUE TITLE
Documentation OneDrive GetUrl (GetWebPath)

### ISSUE THREAD

**Issue by tdalon** [cristianbuse/VBA-FileTools#9]
Hi Cristian
I would be interested in your solution see issue title and related post: https://stackoverflow.com/questions/72100364/get-url-for-file-stored-in-onedrive-with-excel-vba/74165973#74165973
to port it to AutoHotkey.
Could you maybe document/explain a bit in a few sentences how you've achieved this?
I understood you are reading some .dat files, right?

Many thanks for sharing your work and your time
Kind Regards,
Thierry

**Comment by cristianbuse** [comment]
Hi @tdalon ,

The author of the post you've linked above has also posted [this](https://stackoverflow.com/a/73577057/8488913) on Stack Overflow. His solution has a detailed explanation at the top of the module and you can find it [here](https://gist.github.com/guwidoe/038398b6be1b16c458365716a921814d). Moreover, his solution works for Mac as well, although I am not sure you need that.

My plan is to rewrite this repo at which point I will also add documentation and proper testing but that won't happen in the next few weeks/months due to time constraints.

I hope Guido's comments are enough to satisfy your needs.

Regards,
Cristian
